# Generated by Django 4.1.1 on 2022-09-19 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_coursecategory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='featured_image',
            field=models.ImageField(null=True, upload_to='course_images/'),
        ),
        migrations.AddField(
            model_name='course',
            name='technologies',
            field=models.TextField(null=True),
        ),
    ]
